default_agent: citysearch
agents:
  citysearch:
    name: citysearch
    entrypoint: /Users/skoppar/workspace/sample-gen-ai-evaluations-workshop/05-framework-specific-evaluations/05-02-AgentCore/citysearch.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::146666888814:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-672e22fb7a
      execution_role_auto_create: false
      account: '146666888814'
      region: us-east-1
      ecr_repository: 146666888814.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-citysearch
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: citysearch-583XaH96wT
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:146666888814:runtime/citysearch-583XaH96wT
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-citysearch-builder
      execution_role: arn:aws:iam::146666888814:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-672e22fb7a
      source_bucket: bedrock-agentcore-codebuild-sources-146666888814-us-east-1
    authorizer_configuration: null
    oauth_configuration: null
